"""学習シナリオの共有定義."""

SCENARIO_PRESETS = [
    {
        "label": "①線形変調限界",
        "hint": "V_LL を 180V 付近まで上げると m_a が 1 に近づき、184V 超でクランプ表示へ切り替わる。",
        "focus": "変調率 m_a と線形変調限界の関係を確認する。",
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 141.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "pwm_mode": "natural",
        "fft_target": "voltage",
        "fft_window": "hann",
    },
    {
        "label": "②キャリア周波数",
        "hint": "f_c を 1kHz から増やすとキャリア高調波ピークが高周波側へ移動し、電流リプルが減少する。",
        "focus": "スイッチング周波数と高調波分布の関係を観察する。",
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 141.0,
            "f": 50.0,
            "f_c": 1.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "pwm_mode": "natural",
        "fft_target": "voltage",
        "fft_window": "hann",
    },
    {
        "label": "③L平滑効果",
        "hint": "L = 0.1mH で電流リプルが大きく、50mH まで上げると正弦波に近づく。",
        "focus": "RL 負荷の平滑効果と高周波抑制を比較する。",
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 141.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 0.1,
        },
        "pwm_mode": "natural",
        "fft_target": "current",
        "fft_window": "hann",
    },
    {
        "label": "④位相遅れ",
        "hint": "L = 50mH, R = 5Ω で PF1 が小さくなり、電流が電圧から大きく遅れる。",
        "focus": "cos(phi) と FFT ベースの PF1 を比較する。",
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 141.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 5.0,
            "L": 50.0,
        },
        "pwm_mode": "natural",
        "fft_target": "current",
        "fft_window": "hann",
    },
    {
        "label": "⑤過変調",
        "hint": "V_LL = 220V で m_a > 1。Overmod View ならクランプせず、参照波と出力の変化を観察できる。",
        "focus": "線形クランプ有無での過変調挙動を比較する。",
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 220.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "pwm_mode": "natural_overmod",
        "fft_target": "voltage",
        "fft_window": "hann",
    },
]
