# SPDX-License-Identifier: MIT
"""学習シナリオの共有定義."""

SCENARIO_PRESETS = [
    {
        "id": "linear_limit",
        "label": "①線形変調限界",
        "hint": "最初は①変調信号と③線間電圧だけに注目。V_LL を上げると m_a が上がり、上限でクランプ表示に切り替わる。",
        "focus": "V_LL 指令と m_a、線形上限のつながりを最初に掴む。",
        "learning_objective": "出力指令を上げたときに、どこで線形関係が崩れるかを説明できる。",
        "prerequisites": [
            "変調方式は三角波比較（carrier）を選ぶ。",
            "Overmod View は OFF から始める。",
            "V_dc, f, f_c は固定したまま比較する。",
        ],
        "procedure": [
            "V_LL を 141V から 200V 以上へ少しずつ上げる。",
            "m_a の表示とクランプ表示の有無を確認する。",
            "同じ条件で Overmod View を ON にして違いを確認する。",
        ],
        "expected_observation": [
            {
                "text": "m_a が 1.0 近傍へ上昇する。",
                "metric": "m_a",
                "comparison": "ge",
                "value": 0.98,
            },
            {
                "text": "Overmod View OFF では線形上限で波形が飽和する。",
            },
        ],
        "uncertainty_notes": [
            "厳密な境界値は表示丸めと周波数条件でわずかに変動する。",
        ],
        "recommended_compare_modes": ["carrier", "carrier_third_harmonic", "space_vector"],
        "tags": ["linear_limit", "overmod", "ma"],
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 141.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "modulation_mode": "carrier",
        "overmod_view": False,
        "fft_target": "voltage",
        "fft_window": "hann",
    },
    {
        "id": "carrier_frequency",
        "label": "②キャリア周波数",
        "hint": "次は⑥FFTを見る。f_c を上げると高調波ピークが右へ移動し、電流リプルが下がりやすくなる。",
        "focus": "f_c と FFT の見え方（電圧/電流）の関係を掴む。",
        "learning_objective": "m_f を上げると何が改善しやすいかを説明できる。",
        "prerequisites": [
            "V_dc, V_LL, f, R, L は固定して比較する。",
            "FFT 窓は Hann に固定する。",
        ],
        "procedure": [
            "f_c を 1kHz から 10kHz へ上げる。",
            "FFT の主ピーク帯域が右へ移ることを確認する。",
            "相電流のリプル変化も一緒に確認する。",
        ],
        "expected_observation": [
            {
                "text": "周波数変調率 m_f が増加する。",
                "metric": "m_f",
                "comparison": "ge",
                "value": 20.0,
            },
            {
                "text": "キャリア高調波群が高周波側へ移動する。",
            },
        ],
        "uncertainty_notes": [
            "THD_V は生PWM電圧基準のため、単純な大小比較のみで良否を決めない。",
        ],
        "recommended_compare_modes": ["carrier", "carrier_two_phase"],
        "tags": ["carrier_frequency", "harmonics", "mf"],
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 141.0,
            "f": 50.0,
            "f_c": 1.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "modulation_mode": "carrier",
        "overmod_view": False,
        "fft_target": "voltage",
        "fft_window": "hann",
    },
    {
        "id": "inductance_smoothing",
        "label": "③L平滑効果",
        "hint": "⑤相電流を主に見る。L を上げるとギザギザが減り、電流が滑らかになる。",
        "focus": "L の変更が電流波形と THD_I にどう効くかを確認する。",
        "learning_objective": "インダクタが高周波成分を抑える役割を説明できる。",
        "prerequisites": [
            "R は固定し、L だけを変える。",
            "評価は相電流 i_u と THD_I を優先する。",
        ],
        "procedure": [
            "L を 0.1mH から 50mH へ上げる。",
            "電流波形の高周波リプルを比較する。",
            "FFT 表示対象を i_u にして THD_I を確認する。",
        ],
        "expected_observation": [
            {
                "text": "電流の高周波成分が減少し、THD_I が低下傾向になる。",
            },
            {
                "text": "位相遅れ（phi）が増える傾向を示す。",
            },
        ],
        "uncertainty_notes": [
            "THD_I の絶対値は f_c と窓関数設定の影響を受ける。",
        ],
        "recommended_compare_modes": ["carrier"],
        "tags": ["inductance", "ripple", "current"],
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 141.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 0.1,
        },
        "modulation_mode": "carrier",
        "overmod_view": False,
        "fft_target": "current",
        "fft_window": "hann",
    },
    {
        "id": "phase_lag",
        "label": "④位相遅れ",
        "hint": "理論比較パネルを見る。L/R を大きくすると電流が遅れ、PF1 が下がる。",
        "focus": "位相遅れ、cos(phi)、PF1 の関係を同時に確認する。",
        "learning_objective": "電流遅れが力率低下につながる理由を説明できる。",
        "prerequisites": [
            "FFT 表示対象は i_u に設定する。",
            "R と L の比率を変えて時定数差を作る。",
        ],
        "procedure": [
            "R=5Ω, L=50mH の状態を確認する。",
            "cos(phi) と PF1(FFT) の値を比較する。",
            "R を増やして位相遅れが減ることを確認する。",
        ],
        "expected_observation": [
            {
                "text": "PF1 が 1 未満で、位相遅れに応じて低下する。",
                "metric": "PF1",
                "comparison": "le",
                "value": 0.95,
            },
            {
                "text": "phi が正（遅れ）として表示される。",
            },
        ],
        "uncertainty_notes": [
            "PF1 は基本波のみの力率であり、全高調波を含む総合力率とは異なる。",
        ],
        "recommended_compare_modes": ["carrier"],
        "tags": ["power_factor", "phase", "rl_load"],
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 141.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 5.0,
            "L": 50.0,
        },
        "modulation_mode": "carrier",
        "overmod_view": False,
        "fft_target": "current",
        "fft_window": "hann",
    },
    {
        "id": "svpwm_compare",
        "label": "⑤SVPWM比較",
        "hint": "ここから方式比較。carrier と space_vector を切り替えて、同じ条件で V1 と波形の差を確認する。",
        "focus": "連続PWM同士の電圧利用率差を比較する。",
        "learning_objective": "零相注入で線形領域が広がる効果を説明できる。",
        "prerequisites": [
            "比較モードは carrier と space_vector を使う。",
            "V_dc, f_c, 負荷条件は固定する。",
        ],
        "procedure": [
            "V_LL を 170-190V 付近に設定する。",
            "carrier と space_vector を切り替える。",
            "V1, THD_V, m_a_limit を比較する。",
        ],
        "expected_observation": [
            {
                "text": "高変調条件で space_vector 側の有効利用率が高い傾向を示す。",
            },
            {
                "text": "m_a が高いほど方式差が見えやすい。",
            },
        ],
        "uncertainty_notes": [
            "低変調率では差が小さく、視覚的に判別しにくい場合がある。",
        ],
        "recommended_compare_modes": ["carrier", "space_vector"],
        "tags": ["svpwm", "zero_sequence", "voltage_utilization"],
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 180.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "modulation_mode": "space_vector",
        "overmod_view": False,
        "fft_target": "voltage",
        "fft_window": "hann",
    },
    {
        "id": "dpwm_compare",
        "label": "⑥二相変調(DPWM)",
        "hint": "連続PWMと二相変調を切り替え、②スイッチングパターンでクランプ区間を先に確認する。",
        "focus": "クランプ区間と高調波分布の変化を比較する。",
        "learning_objective": "DPWM でスイッチング回数が減る見え方を説明できる。",
        "prerequisites": [
            "比較対象として carrier を用意する。",
            "同一 V_dc, V_LL, f, f_c 条件で比較する。",
        ],
        "procedure": [
            "carrier と carrier_two_phase を切り替える。",
            "スイッチングパターンで 60 度クランプ区間を確認する。",
            "FFT で低次成分変化を比較する。",
        ],
        "expected_observation": [
            {
                "text": "二相変調でクランプ区間が視認できる。",
            },
            {
                "text": "スペクトル分布が連続PWMと異なる。",
            },
        ],
        "uncertainty_notes": [
            "総損失最小点は導通損とスイッチング損の両方に依存する。",
        ],
        "recommended_compare_modes": ["carrier", "carrier_two_phase"],
        "tags": ["dpwm", "clamp", "switching_loss"],
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 170.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "modulation_mode": "carrier_two_phase",
        "overmod_view": False,
        "fft_target": "voltage",
        "fft_window": "hann",
    },
    {
        "id": "third_harmonic_compare",
        "label": "⑦三倍高調波注入",
        "hint": "carrier と三倍高調波注入を切り替え、①変調信号の形と V1 の違いを見る。",
        "focus": "三倍高調波注入で線形上限が広がることを確認する。",
        "learning_objective": "零相三倍高調波注入の効果を定性的・定量的に説明できる。",
        "prerequisites": [
            "carrier と carrier_third_harmonic を比較する。",
            "高変調率条件で差を観測する。",
        ],
        "procedure": [
            "V_LL を高めに設定して両方式を切り替える。",
            "V1 と m_a_limit の違いを比較する。",
            "FFT でスペクトル分布の差を確認する。",
        ],
        "expected_observation": [
            {
                "text": "線形上限拡張により高変調での運転余裕が増える。",
            },
            {
                "text": "SVPWM と類似した利用率向上傾向を示す。",
            },
        ],
        "uncertainty_notes": [
            "THD の優劣は負荷条件と評価帯域に依存する。",
        ],
        "recommended_compare_modes": ["carrier", "carrier_third_harmonic", "space_vector"],
        "tags": ["third_harmonic", "zero_sequence", "voltage_utilization"],
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 180.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "modulation_mode": "carrier_third_harmonic",
        "overmod_view": False,
        "fft_target": "voltage",
        "fft_window": "hann",
    },
    {
        "id": "svpwm_two_phase_compare",
        "label": "⑧SVPWM二相変調比較",
        "hint": "SVPWM の連続/不連続を比較する。②スイッチングと⑥FFTを行き来して確認する。",
        "focus": "space_vector と space_vector_two_phase の差を直接比較する。",
        "learning_objective": "SVPWM 系における連続/不連続変調の違いを整理できる。",
        "prerequisites": [
            "space_vector と space_vector_two_phase を同条件で比較する。",
            "FFT は v_uv 表示を優先する。",
        ],
        "procedure": [
            "modulation_mode を空間ベクトルと空間ベクトル(二相変調)で切り替える。",
            "スイッチングパターンでクランプ区間の有無を確認する。",
            "FFT でスペクトル差を確認する。",
        ],
        "expected_observation": [
            {
                "text": "space_vector_two_phase でクランプ区間が現れる。",
            },
            {
                "text": "THD_V や低次成分分布が連続SVPWMと異なる。",
            },
        ],
        "uncertainty_notes": [
            "低変調率では差が視覚的に小さい場合がある。",
        ],
        "recommended_compare_modes": ["space_vector", "space_vector_two_phase"],
        "tags": ["svpwm", "dpwm", "two_phase"],
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 170.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "modulation_mode": "space_vector_two_phase",
        "overmod_view": False,
        "fft_target": "voltage",
        "fft_window": "hann",
    },
    {
        "id": "overmodulation",
        "label": "⑨過変調",
        "hint": "最後に過変調を確認。Overmod View OFF/ON を切り替え、線形クランプの有無と歪み増加を比較する。",
        "focus": "線形クランプ有無での過変調挙動を比較する。",
        "learning_objective": "過変調での波形歪みと利用率のトレードオフを説明できる。",
        "prerequisites": [
            "V_dc は 300V に固定する。",
            "Overmod View の ON/OFF を同一条件で比較する。",
        ],
        "procedure": [
            "V_LL を 220V に設定して Overmod View OFF を確認する。",
            "同条件で Overmod View ON に切り替える。",
            "m_a_raw, m_a_limit, 波形歪みの違いを比較する。",
        ],
        "expected_observation": [
            {
                "text": "選択中方式の線形上限を超えるとクランプまたは過変調表示になる。",
            },
            {
                "text": "Overmod View ON で線形クランプ無効の挙動を示す。",
            },
        ],
        "uncertainty_notes": [
            "歪み評価は THD だけでなく低次成分の増加も確認する。",
        ],
        "recommended_compare_modes": ["carrier", "space_vector"],
        "tags": ["overmodulation", "clamp", "nonlinear"],
        "sliders": {
            "V_dc": 300.0,
            "V_ll": 220.0,
            "f": 50.0,
            "f_c": 5.0,
            "t_d": 0.0,
            "V_on": 0.0,
            "R": 10.0,
            "L": 10.0,
        },
        "modulation_mode": "carrier",
        "overmod_view": True,
        "fft_target": "voltage",
        "fft_window": "hann",
    },
]
